# Generated by Django 3.2.9 on 2021-11-23 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(default='', max_length=100)),
                ('job_profile', models.CharField(max_length=50)),
                ('work_experience', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=2)),
                ('Institution', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=100)),
                ('YearOfPassing', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoundDetails',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.PositiveIntegerField()),
                ('about', models.TextField(max_length=500)),
                ('exp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intexp.experience')),
            ],
        ),
    ]
