# Generated by Django 3.2.9 on 2021-11-23 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intexp', '0002_experience_isapproved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Age',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='DOB',
            field=models.DateField(default=datetime.datetime(2021, 11, 23, 18, 46, 38, 295666, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
