# Generated by Django 3.2.9 on 2021-11-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intexp', '0003_auto_20211123_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='isModerator',
            field=models.BooleanField(default=False),
        ),
    ]
